import localFont from "next/font/local";
import "./globals.css";
import { Work_Sans } from '@next/font/google';

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const keepcalm = localFont({
  src: "./fonts/KeepCalm-Medium.ttf",
  variable: "--font-keep-calm",
  weight: "100 900",
});

const workSans = Work_Sans({
  subsets: ['latin'], 
  weight: ['400', '500', '700'], 
  variable: '--font-work-sans', 
});

export const metadata = {
  title: "Metacces",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`  ${keepcalm.variable} ${workSans.variable} antialiased`}
      >
        <div className="min-h-screen  bg-[#080717] text-white">
          {children}
        </div>
      </body>
    </html>
  );
}
